// This file is generated by snippet_process.py, do not edit it manually.

package indi.wenyan.content.gui;

import java.util.List;

public enum Snippets {;
    public record Context(String value) { }
    
    public static final SnippetSet VARIABLE_STMT = new SnippetSet("variable_stmt",
        SnippetSet.snippet("reference_statement", "夫{DATA}。{NONE}"),
        SnippetSet.snippet("declare_statement", "吾有一{TYPE}曰{DATA}。{NONE}"),
        SnippetSet.snippet("define_statement", "名之曰{ID}。{NONE}"),
        SnippetSet.snippet("assign_statement", "昔之{ID}者。今{DATA}是矣。{NONE}")
    );

    public static final SnippetSet CONTROL_STMT = new SnippetSet("control_stmt",
        SnippetSet.snippet("if_statement", "若{BOOL}者。\n  {STMT}\n也。{NONE}"),
        SnippetSet.snippet("if_else_statement", "若{BOOL}者。\n  {STMT}\n若非。\n  {STMT}\n也。{NONE}"),
        SnippetSet.snippet("for_statement", "凡{DATA}中之{ID}。\n  {STMT}\n云云。{NONE}"),
        SnippetSet.snippet("for_enum_statement", "為是{INT}遍。\n  {STMT}\n云云。{NONE}"),
        SnippetSet.snippet("return_statement", "乃得{DATA}。{NONE}"),
        SnippetSet.snippet("break", "乃止。"),
        SnippetSet.snippet("continue", "乃止是遍。")
    );

    public static final SnippetSet CALL_STATEMENT = new SnippetSet("call_statement",
        SnippetSet.snippet("add_call", "加{DATA}以{DATA}。{NONE}"),
        SnippetSet.snippet("sub_call", "減{DATA}以{DATA}。{NONE}"),
        SnippetSet.snippet("mul_call", "乘{DATA}以{DATA}。{NONE}"),
        SnippetSet.snippet("div_call", "除{DATA}以{DATA}。{NONE}"),
        SnippetSet.snippet("function_post_call", "取{INT}以施{ID}。{NONE}"),
        SnippetSet.snippet("function_pre_call", "施{ID}。於{DATA}。{NONE}")
    );

    public static final SnippetSet INT_LITERAL = new SnippetSet("int_literal",
        SnippetSet.snippet("0", "零"),
        SnippetSet.snippet("1", "一"),
        SnippetSet.snippet("2", "二"),
        SnippetSet.snippet("3", "三"),
        SnippetSet.snippet("4", "四"),
        SnippetSet.snippet("5", "五"),
        SnippetSet.snippet("6", "六"),
        SnippetSet.snippet("7", "七"),
        SnippetSet.snippet("8", "八"),
        SnippetSet.snippet("9", "九"),
        SnippetSet.snippet("10", "十")
    );

    public static final SnippetSet BOOL_LITERAL = new SnippetSet("bool_literal",
        SnippetSet.snippet("true", "陽"),
        SnippetSet.snippet("false", "陰"),
        SnippetSet.snippet("greater_than", "{DATA}大於{DATA}"),
        SnippetSet.snippet("less_than", "{DATA}小於{DATA}"),
        SnippetSet.snippet("equal", "{DATA}等於{DATA}")
    );

    public static final SnippetSet STRING_LITERAL = new SnippetSet("string_literal",
        SnippetSet.snippet("string", "「「{NONE}」」")
    );

    public static final SnippetSet TYPE_LITERAL = new SnippetSet("type_literal",
        SnippetSet.snippet("number_type", "數"),
        SnippetSet.snippet("list_type", "列"),
        SnippetSet.snippet("string_type", "言"),
        SnippetSet.snippet("bool_type", "爻")
    );

    public static final SnippetSet IDENTIFIER = new SnippetSet("identifier",
        SnippetSet.snippet("甲", "「甲」"),
        SnippetSet.snippet("乙", "「乙」"),
        SnippetSet.snippet("丙", "「丙」"),
        SnippetSet.snippet("丁", "「丁」"),
        SnippetSet.snippet("戊", "「戊」")
    );

    public static final SnippetSet NEW_LINE = new SnippetSet("new_line",
        SnippetSet.snippet("new_line", "\n{STMT}")
    );

    
    public static final List<SnippetSet> DATA_CONTEXT = List.of(INT_LITERAL, BOOL_LITERAL, STRING_LITERAL, IDENTIFIER);
    public static final List<SnippetSet> TYPE_CONTEXT = List.of(TYPE_LITERAL);
    public static final List<SnippetSet> ID_CONTEXT = List.of(IDENTIFIER);
    public static final List<SnippetSet> BOOL_CONTEXT = List.of(BOOL_LITERAL);
    public static final List<SnippetSet> INT_CONTEXT = List.of(INT_LITERAL);
    public static final List<SnippetSet> STMT_CONTEXT = List.of(VARIABLE_STMT, CONTROL_STMT, CALL_STATEMENT);
    public static final List<SnippetSet> NONE_CONTEXT = List.of(NEW_LINE);


    public static final List<SnippetSet> DEFAULT_CONTEXT = STMT_CONTEXT;

    public static int contextColor(Context context) {
        return switch (context.value()) {
            case "DATA" -> 0xFFFFB6C1;
            case "TYPE" -> 0xFFADD8E6;
            case "ID" -> 0xFF90EE90;
            case "BOOL" -> 0xFFFFFFE0;
            case "INT" -> 0xFFD3D3D3;
            case "STMT" -> 0xFFFFFFFF;
            case "NONE" -> 0xFFF0E68C;
            default -> throw new IllegalStateException("Unexpected value: " + context.value());
        };
    }

    public static List<SnippetSet> getSnippets(Context context) {
        return switch (context.value()) {
            case "DATA" -> DATA_CONTEXT;
            case "TYPE" -> TYPE_CONTEXT;
            case "ID" -> ID_CONTEXT;
            case "BOOL" -> BOOL_CONTEXT;
            case "INT" -> INT_CONTEXT;
            case "STMT" -> STMT_CONTEXT;
            case "NONE" -> NONE_CONTEXT;
            default -> throw new IllegalStateException("Unexpected value: " + context.value());
        };
    }
}
