# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.42-beta
neo_version_range=[26.1.2.42-beta,)
loader_version_range=[1,)

jei_version=29.3.0.22
jei_minecraft_version=26.1.1
rei_version=21.11.814
wthit_version=18.2.2
jade_version=26.0.6

# Pick which item list mod gets picked at runtime in dev
# Available options: rei, jei, none
runtime_itemlist_mod=jei

# Set to wthit, jade or none to pick which tooltip mod gets picked at runtime
# for the dev environment.
runtime_tooltip_mod=jade

## Mod Properties
mod_id=wenyan_programming
mod_name=Wenyan Programming
mod_license=GNU LGPLv3
mod_version=1.0.1
mod_group_id=indi.wenyan
