nav:
  - index.md
  - quick_start.md
  - varible.md
  - calculation.md
  - control.md
  - function.md
  - object.md
  - import.md
  - advanced.md
  - misc.md
  - syntax_cheatsheet.md
  - quick_reference.md
