// this code is generated by snippet_process.py, do not edit it manually.

package indi.wenyan.judou.runtime.test_utils;

import indi.wenyan.judou.structure.values.IWenyanValue;
import indi.wenyan.judou.utils.WenyanValues;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.List;

public class generated_WenyanProgramTestData implements ArgumentsProvider {
    public record TestData(String code, List<IWenyanValue> output) {}

    public static final TestData[] TEST_DATA = {
//             new TestData("吾有一言。曰「「問天地好在。」」。書之。", List.of(WenyanValues.of("問天地好在。"))),
//             new TestData("吾有一數。曰三。名之曰「甲」。\n為是「甲」遍。\n	吾有一言。曰「「問天地好在。」」。書之。\n云云。", List.of(WenyanValues.of("問天地好在。"),WenyanValues.of("問天地好在。"),WenyanValues.of("問天地好在。"))),
             new TestData("吾有一術。名之曰「考拉茲」。欲行是術。必先得一數。曰「甲」。乃行是術曰。\n	有數零。名之曰「總」。\n	為是九千九百九十九遍。\n		若「甲」等於一者。乃得「總」。\n		若非。\n			除「甲」以二。所餘幾何。名之曰「丙」。\n			若「丙」等於零者。\n			  除「甲」以二。名之曰「半」。昔之「甲」者。今「半」是矣\n			若非。\n				乘「甲」以三。名之曰「丁」。加一於「丁」。名之曰「戊」。昔之「甲」者。今「戊」是矣\n			也。\n			加「總」以一。名之曰「己」。\n			昔之「總」者。今「己」是矣也。\n	云云。\n是謂「考拉茲」之術也。\n\n\n施「考拉茲」於一十八。書之。\n施「考拉茲」於一百二十三。書之。\n施「考拉茲」於九百七十八。書之。\n施「考拉茲」於六。書之。\n", List.of(WenyanValues.of(20),WenyanValues.of(46),WenyanValues.of(49),WenyanValues.of(8))),
//             new TestData("吾有一術。名之曰「歐幾里得法」。\n欲行是術。必先得二數。\n曰「甲」。曰「乙」。\n乃行是術曰。\n		吾有一數。名之曰「回」。\n		若「乙」等於零者。乃得「甲」。\n		若非\n			吾有一數。名之曰「削除」。\n			除「甲」以「乙」所餘幾何。昔之「削除」者。今其是矣。\n			施「歐幾里得法」於「乙」。於「削除」。\n			昔之「回」者。今其是矣。\n		也\n		乃得「回」。\n是謂「歐幾里得法」之術也。\n\n吾有一術。名之曰「互質」。\n欲行是術。必先得二數。\n曰「甲」。曰「乙」。\n乃行是術曰。\n		吾有一數。名之曰「回」。\n		施「歐幾里得法」於「甲」。於「乙」。昔之「回」者。今其是矣。\n		若「回」等於一者。乃得陽。若非。乃得陰。也。\n是謂「互質」之術也。\n\n吾有一術。名之曰「歐拉餘數」。\n欲行是術。必先得一數。\n曰「甲」。\n乃行是術曰。\n	注曰。「「非最優解矣。吾算術及數論廢也」」\n	吾有二數。曰二。曰一。名之曰「埃」。曰「積」\n	恆為是。\n		若「甲」不大於「埃」者。乃止。也。\n		吾有一爻。名之曰「回」。\n		施「互質」於「甲」。於「埃」。昔之「回」者。今其是矣。\n		若「回」者加「積」以一。名之曰「積」。也。\n		加「埃」以一。名之曰「埃」。\n	云云\n	乃得「積」。\n是謂「歐拉餘數」之術也。\n\n施「歐幾里得法」於一千零七十一於四百六十二。書之。\n施「歐幾里得法」於一百二十三於四。書之。\n\n施「互質」於一百二十三於四。書之。\n施「互質」於四於二。書之。\n\n施「歐拉餘數」於二。書之。\n施「歐拉餘數」於十二。書之。\n施「歐拉餘數」於十三。書之。\n施「歐拉餘數」於十六。書之。\n施「歐拉餘數」於二百五十五。書之。", List.of(WenyanValues.of(21),WenyanValues.of(1),WenyanValues.of(true),WenyanValues.of(false),WenyanValues.of(1),WenyanValues.of(4),WenyanValues.of(12),WenyanValues.of(8),WenyanValues.of(128))),
//             new TestData("吾有一術。名之曰「階乘」。欲行是術。必先得一數。曰「甲」。乃行是術曰。\n	若「甲」等於一者。\n		乃得「甲」。\n	若非。\n		減「甲」以一。名之曰「乙」。\n		施「階乘」於「乙」。名之曰「丙」。\n		乘「丙」以「甲」。名之曰「丁」。\n		乃得「丁」\n	也。\n是謂「階乘」之術也。\n\n施「階乘」於五。書之。", List.of(WenyanValues.of(120))),
//             new TestData("吾有一術。名之曰「斐波那契」。欲行是術。必先得一數。曰「甲」。乃行是術曰。\n	若「甲」等於零者乃得零也\n	若「甲」等於一者乃得一也\n	減「甲」以一。減「甲」以二。名之曰「乙」。曰「丙」。\n	施「斐波那契」於「乙」。名之曰「丁」。\n	施「斐波那契」於「丙」。名之曰「戊」。\n	加「丁」以「戊」。名之曰「己」。\n	乃得「己」。\n是謂「斐波那契」之術也。\n\n施「斐波那契」於十二。書之。", List.of(WenyanValues.of(144))),
//             new TestData("吾有一術。名之曰「斐氏列」。\n\n欲行是術。必先得一數。曰「因」。乃行是術曰。\n		有數零。名之曰「頭」。\n	有數一。名之曰「尾」。\n		有數一。名之曰「計」。\n	有數零。名之曰「果」。\n\n	若「因」等於零者。昔之「果」者。今「因」是矣云云。\n	若「因」等於一者。昔之「果」者。今「因」是矣云云。\n\n		恆為是。若「計」不小於「因」者乃止也。\n				加「頭」以「尾」。昔之「果」者。今其是矣。\n				昔之「頭」者。今「尾」是矣。\n				昔之「尾」者。今「果」是矣。\n				加「計」以一。昔之「計」者。今其是矣。\n		云云。\n\n		乃得「果」\n是謂「斐氏列」之術也。\n\n施「斐氏列」於十。書之。\n", List.of(WenyanValues.of(55))),
//             new TestData("吾有一術。名之曰「大衍求一」。欲行是術。必先得二數。曰「奇」。曰「定」。乃行是術曰。\n注曰「「\n	大衍求一術云。\n	置奇右上。定居右下。立天元一於左上。\n	先以右上除右下。所得商數與左上一相生。入左下。然後乃以右行上下。\n	以少除多。遞互除之。所得商數隨即遞互累乘。歸左行上下。\n	須使右上末後奇一而止。乃驗左上所得。以為乘率。\n	或奇數已見單一者。便為乘率。\n」」\n	若「奇」等於〇者。乃得〇也。\n	若「奇」等於一者。乃得一也。\n\n	有數一。名之曰「天元」。\n	吾有四數。曰「奇」曰「定」曰「天元」曰〇。\n		名之曰「右上」曰「右下」曰「左上」曰「左下」。\n\n	恆為是。\n		若「右上」等於一者。乃得「左上」也。\n\n		除「右下」以「右上」。所餘幾何。名之曰「餘數」。\n		減「右下」以「餘數」。除其以「右上」。名之曰「商數」。\n		乘「商數」以「左上」。加「左下」以其。昔之「左下」者。今其是矣。\n		昔之「右下」者。今「餘數」是矣。\n\n		若「右下」等於〇者。乃得〇也。\n		注曰。「「若右下等於〇者。曰奇數與定數不互素。無乘率也。」」\n\n		減「右上」以一，除其以「右下」。所餘幾何。加其以一。名之曰「餘數」。\n		減「右上」以「餘數」。除其以「右下」。名之曰「商數」。\n		乘「商數」以「左下」。加「左上」以其。昔之「左上」者。今其是矣。\n		昔之「右上」者。今「餘數」是矣。\n	云云。\n是謂「大衍求一」之術也。\n\n\n施「大衍求一」於四十九。於十四萬二千八百五十七。名之曰「乘率」。\n乘四十九以「乘率」。除其以十四萬二千八百五十七。所餘幾何。書之。\n", List.of(WenyanValues.of(1))),
//             new TestData("夫一書之\n夫零書之\n夫「「aaa」」書之\n夫一又五分書之\n夫陽書之\n夫一夫其書之\n夫一大於二書之\n夫二等於二書之\n夫陽等於一書之", List.of(WenyanValues.of(1),WenyanValues.of(0),WenyanValues.of("aaa"),WenyanValues.of(1.5),WenyanValues.of(true),WenyanValues.of(1),WenyanValues.of(false),WenyanValues.of(true),WenyanValues.of(false))),
//             new TestData("吾有一數書之\n吾有一數曰一書之\n吾有二數曰一曰二書之\n吾有一數曰一又五分書之\n吾有一言書之\n吾有二言曰一曰「「aaa」」書之\n吾有一言曰陽書之\n吾有一爻曰其書之\n吾有一列書之", List.of(WenyanValues.of(0),WenyanValues.of(1),WenyanValues.of(1),WenyanValues.of(2),WenyanValues.of(1.5),WenyanValues.of(""),WenyanValues.of("一"),WenyanValues.of("aaa"),WenyanValues.of("陽"),WenyanValues.of(true),WenyanValues.of(List.of())))
    };
}
