import json

code_template = """// this code is generated by snippet_process.py, do not edit it manually.

package indi.wenyan.interpreter.runtime.utils;

import indi.wenyan.interpreter.structure.values.IWenyanValue;
import indi.wenyan.interpreter.utils.WenyanValues;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.List;

public class generated_WenyanProgramTestData implements ArgumentsProvider {
    public record TestData(String code, List<IWenyanValue> output) {}

    public static final TestData[] TEST_DATA = {/test/
    };
}
"""
test_template = """
             new TestData(/code/, List.of(/outputs/)),"""
outputs_template = "WenyanValues.of(/output/),"


def java_string(s):
    if type(s) == type(1):
        return str(s)
    elif type(s) == type(1.0):
        return str(s)
    elif type(s) == type(""):
        return '"' + s.replace('"', '\\"').replace('\n', '\\n') + '"'
    elif type(s) == type(True):
        return "true" if s else "false"


data = {}
with open("test_data.json", "r", encoding="utf-8") as f:
    data = json.load(f)
test_str = ""
for category in data["pass_cases"].values():
    for test in category:
        code = test["code"]
        output = test["output"]
        outputs_str = ""
        for item in output:
            if type(item) == type([]):
                if len(item) == 0:
                    outputs_str += outputs_template.replace("/output/", "List.of()")
                else:
                    outputs_str += outputs_template.replace("/output/", (
                        "".join(
                            outputs_template.replace("/output/", java_string(i)) for i in item))[
                        :-1])
            else:
                outputs_str += outputs_template.replace("/output/", java_string(item))
        test_str += test_template.replace("/code/", java_string(code)) \
            .replace("/outputs/", outputs_str[:-1])
code = code_template.replace("/test/", test_str[:-1])

with open("generated_WenyanProgramTestData.java", "w", encoding="utf-8") as f_out:
    f_out.write(code)
