import hashlib
import json
import os
import sys

if not os.path.exists("py_map.json") or (len(sys.argv) > 1 and sys.argv[1] == "-f"):
    from pypinyin import pinyin, lazy_pinyin, Style

    py_map = {}
    with open("token_list.txt", "r", encoding="utf-8") as f:
        for l in f.readlines():
            l = l[:-1]
            if len(l) > 1:
                s = "".join(["".join(i) for i in pinyin(l, style=Style.FIRST_LETTER)])
                py_map[s] = py_map.get(s, [])
                py_map[s].append(l)
            s = "".join(lazy_pinyin(l))
            py_map[s] = py_map.get(s, [])
            py_map[s].append(l)
    json.dump(py_map, open("py_map.json", "w", encoding="utf-8"))


py_map = json.load(open("py_map.json", "r", encoding="utf-8"))
py_map_extra = json.load(open("py_map_extra.json", "r", encoding="utf-8"))

# merge
for k in py_map_extra:
    py_map[k] = py_map.get(k, [])
    py_map[k].extend(py_map_extra[k])

code_template = """// This file is generated by snippet_process.py, do not edit it manually.

package indi.wenyan.content.gui.code_editor;

import java.util.Collection;
import java.util.List;
import java.util.SortedMap;
import java.util.TreeMap;

public enum Completions {;
    static final SortedMap<String, Collection<Completion>> map = new TreeMap<>() {{
        /entry/
    }};
}
"""

entry_template = '        put("/k/", List.of(/warp_v/));\n'
warp_v_template = 'new Completion("/v/"),'

entry = ""
for k in py_map:
    v = py_map[k]
    warp_v = ""
    for i in v:
        warp_v += warp_v_template.replace("/v/", i)
    entry += entry_template.replace("/k/", k) \
        .replace("/warp_v/", warp_v[:-1])
code = code_template.replace("/entry/", entry[8:-1])
with open("../Completions.java", "w", encoding="utf-8") as f_out:
    f_out.write(code)
