import json
import os
import re
import shutil
import toml

java_template = """// This file is generated by snippet_process.py, do not edit it manually.

package indi.wenyan.content.gui.code_editor;

import lombok.Getter;

import java.util.List;

public enum Snippets {;
    /snippet_set/
    /snippet_context/
}
"""

snippet_set_template = """
    public static final SnippetSet /snippet_set_title_upper/ = new SnippetSet("/snippet_set_title/",
        /snippet/
    );
"""
snippet_template = '        SnippetSet.snippet("/name/", "/content/"),\n'
snippet_template = '        new SnippetSet.Snippet("/name/", List.of(/contents/), List.of(/placeholders/)),\n'
placeholder_template = "\n                new SnippetSet.SnippetPlaceholder(Context./context/, /i/, /j/),"

snippet_context_template = """
    /context_define/

    public static final List<SnippetSet> DEFAULT_CONTEXT = /default_context/;

    public enum Context {
        /context_entry/
        ;

        @Getter private final String value;
        @Getter private final int color;
        Context(String value, int color) {
            this.value = value;
            this.color = color;
        }
    }

    public static List<SnippetSet> getSnippets(Context context) {
        return switch (context) {
            /context_contain/
        };
    }
"""
context_contain_template = '            case /context/ -> /context/_CONTEXT;\n'
context_entry_template = '        /context/("/context/", /color/),\n'
context_define_template = '    public static final List<SnippetSet> /context/_CONTEXT = List.of(/contain/);\n'

data = {}
with open("snippet.json", "r", encoding="utf-8") as f:
    data = json.load(f)
# with open("snippet.toml", "r", encoding="utf-8") as f:
#     data = toml.load(f)
snippet_sets = data["snippet_sets"]
snippet_code = ""
for snippet_set_key in snippet_sets:
    snippet_set = snippet_sets[snippet_set_key]
    title = snippet_set["title"]
    snippets = snippet_set["snippets"]
    snippet_set_title_upper = snippet_set_key.upper().replace(" ", "_")
    snippet_set_title = title.replace(" ", "_").lower()
    snippet_str = ""
    for snippet in snippets:
        name = snippet["name"]
        content = snippet["content"].split("\n")
        contents_code = ""
        placeholders_code = ""
        for i, line in enumerate(content):
            # find {CTX}
            placeholders_iter = re.finditer(r"\{(.*?)\}", line)
            deleted_str = 0
            for p in placeholders_iter:
                placeholders_code += placeholder_template \
                    .replace("/context/", p.group(1)) \
                    .replace("/i/", str(i)) \
                    .replace("/j/", str(p.start() - deleted_str))
                deleted_str += len(p.group())
            contents_code += f'"{re.sub(r"\{(.*?)\}", "", line)}",'
        snippet_str += snippet_template.replace("/name/", name) \
            .replace("/contents/", contents_code[:-1]) \
            .replace("/placeholders/", placeholders_code[:-1])
    snippet_set_code = snippet_set_template \
        .replace("/snippet_set_title_upper/", snippet_set_title_upper) \
        .replace("/snippet_set_title/", snippet_set_title) \
        .replace("/snippet/", snippet_str[8:-2])  # remove last comma
    snippet_code += snippet_set_code
# context
context = data["snippet_context"]
default_context = data["default_context"]
context_color_code = ""
context_contain_code = ""
context_define_code = ""
context_entry_code = ""
for ctx in context:
    ctx_name = ctx["context"]
    ctx_color = ctx["color"]
    ctx_contain = ctx["contain"]
    context_define_code += context_define_template \
        .replace("/context/", ctx_name) \
        .replace("/contain/", ", ".join([s.upper() for s in ctx_contain]))
    context_contain_code += context_contain_template \
        .replace("/context/", ctx_name)
    context_entry_code += context_entry_template \
        .replace("/context/", ctx_name) \
        .replace("/color/", ctx_color)
snippet_context_code = snippet_context_template \
    .replace("/default_context/", default_context) \
    .replace("/context_define/", context_define_code[4:-1]) \
    .replace("/context_contain/", context_contain_code[12:-1]) \
    .replace("/context_entry/", context_entry_code[8:-1])

final_code = java_template \
    .replace("/snippet_set/", snippet_code) \
    .replace("/snippet_context/", snippet_context_code[:-1])
with open("../Snippets.java", "w", encoding="utf-8") as f_out:
    f_out.write(final_code)
