// This file is generated by snippet_process.py, do not edit it manually.

package indi.wenyan.content.gui.code_editor;

import java.util.List;

public enum Snippets {;
    public record Context(String value) { }
    
    public static final SnippetSet VARIABLE_STMT = new SnippetSet("變數",
        SnippetSet.snippet("夫", "夫{DATA}。{NONE}"),
        SnippetSet.snippet("吾有", "吾有一{TYPE}曰{DATA}。{NONE}"),
        SnippetSet.snippet("名之曰", "名之曰{ID}。{NONE}"),
        SnippetSet.snippet("昔之...今", "昔之{ID}者。今{DATA}是矣。{NONE}")
    );

    public static final SnippetSet CONTROL_STMT = new SnippetSet("決策",
        SnippetSet.snippet("若", "若{BOOL}者。\n  {STMT}\n也。{NONE}"),
        SnippetSet.snippet("若...若非", "若{BOOL}者。\n  {STMT}\n若非。\n  {STMT}\n也。{NONE}"),
        SnippetSet.snippet("凡中之", "凡{DATA}中之{ID}。\n  {STMT}\n云云。{NONE}"),
        SnippetSet.snippet("為是...遍", "為是{INT}遍。\n  {STMT}\n云云。{NONE}"),
        SnippetSet.snippet("乃得", "乃得{DATA}。{NONE}"),
        SnippetSet.snippet("乃止", "乃止。"),
        SnippetSet.snippet("乃止是遍", "乃止是遍。")
    );

    public static final SnippetSet CALL_STATEMENT = new SnippetSet("算術",
        SnippetSet.snippet("加", "加{INT}以{INT}。{NONE}"),
        SnippetSet.snippet("減", "減{INT}以{INT}。{NONE}"),
        SnippetSet.snippet("乘", "乘{INT}以{INT}。{NONE}"),
        SnippetSet.snippet("除", "除{INT}以{INT}。{NONE}"),
        SnippetSet.snippet("取以施", "取{INT}以施{ID}。{NONE}"),
        SnippetSet.snippet("施", "施{ID}。於{DATA}。{NONE}")
    );

    public static final SnippetSet INT_LITERAL = new SnippetSet("整數",
        SnippetSet.snippet("0", "零"),
        SnippetSet.snippet("1", "一"),
        SnippetSet.snippet("2", "二"),
        SnippetSet.snippet("3", "三"),
        SnippetSet.snippet("4", "四"),
        SnippetSet.snippet("5", "五"),
        SnippetSet.snippet("6", "六"),
        SnippetSet.snippet("7", "七"),
        SnippetSet.snippet("8", "八"),
        SnippetSet.snippet("9", "九"),
        SnippetSet.snippet("10", "十")
    );

    public static final SnippetSet BOOL_LITERAL = new SnippetSet("布爾",
        SnippetSet.snippet("陽", "陽"),
        SnippetSet.snippet("陰", "陰"),
        SnippetSet.snippet("大於", "{DATA}大於{DATA}"),
        SnippetSet.snippet("小於", "{DATA}小於{DATA}"),
        SnippetSet.snippet("等於", "{DATA}等於{DATA}")
    );

    public static final SnippetSet STRING_LITERAL = new SnippetSet("言語",
        SnippetSet.snippet("言語", "「「{NONE}」」")
    );

    public static final SnippetSet TYPE_LITERAL = new SnippetSet("類",
        SnippetSet.snippet("數", "數"),
        SnippetSet.snippet("列", "列"),
        SnippetSet.snippet("言", "言"),
        SnippetSet.snippet("爻", "爻")
    );

    public static final SnippetSet IDENTIFIER = new SnippetSet("變數",
        SnippetSet.snippet("甲", "「甲」"),
        SnippetSet.snippet("乙", "「乙」"),
        SnippetSet.snippet("丙", "「丙」"),
        SnippetSet.snippet("丁", "「丁」"),
        SnippetSet.snippet("戊", "「戊」")
    );

    public static final SnippetSet NEW_LINE = new SnippetSet("換行",
        SnippetSet.snippet("換行", "\n{STMT}")
    );

    
    public static final List<SnippetSet> DATA_CONTEXT = List.of(INT_LITERAL, BOOL_LITERAL, STRING_LITERAL, IDENTIFIER);
    public static final List<SnippetSet> TYPE_CONTEXT = List.of(TYPE_LITERAL);
    public static final List<SnippetSet> ID_CONTEXT = List.of(IDENTIFIER);
    public static final List<SnippetSet> BOOL_CONTEXT = List.of(BOOL_LITERAL);
    public static final List<SnippetSet> INT_CONTEXT = List.of(INT_LITERAL);
    public static final List<SnippetSet> STMT_CONTEXT = List.of(VARIABLE_STMT, CONTROL_STMT, CALL_STATEMENT);
    public static final List<SnippetSet> NONE_CONTEXT = List.of(NEW_LINE);


    public static final List<SnippetSet> DEFAULT_CONTEXT = STMT_CONTEXT;

    public static int contextColor(Context context) {
        return switch (context.value()) {
            case "DATA" -> 0xFFFFB6C1;
            case "TYPE" -> 0xFFADD8E6;
            case "ID" -> 0xFF90EE90;
            case "BOOL" -> 0xFFFFFFE0;
            case "INT" -> 0xFFD3D3D3;
            case "STMT" -> 0xFFFFFFFF;
            case "NONE" -> 0xFFF0E68C;
            default -> throw new IllegalStateException("Unexpected value: " + context.value());
        };
    }

    public static List<SnippetSet> getSnippets(Context context) {
        return switch (context.value()) {
            case "DATA" -> DATA_CONTEXT;
            case "TYPE" -> TYPE_CONTEXT;
            case "ID" -> ID_CONTEXT;
            case "BOOL" -> BOOL_CONTEXT;
            case "INT" -> INT_CONTEXT;
            case "STMT" -> STMT_CONTEXT;
            case "NONE" -> NONE_CONTEXT;
            default -> throw new IllegalStateException("Unexpected value: " + context.value());
        };
    }
}
